### ISSUE TITLE
您好，请问代码是否完整？

### ISSUE THREAD

**Issue by TK-Operator** [lcy0604/CTRNet-plus#3]
当我想要进行测试时，系统提示
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from models import build_model
  File "/ai/data/styinfy/CTRNet-plus-main/models/__init__.py", line 2, in <module>
    from .ctrnetpp import build
  File "/ai/data/styinfy/CTRNet-plus-main/models/ctrnetpp.py", line 14, in <module>
    from .network import build_discriminator, build_feature_extractor,\
  File "/ai/data/styinfy/CTRNet-plus-main/models/network.py", line 7, in <module>
    from src.models import create_model
ModuleNotFoundError: No module named 'src'
貌似没有src这个文件夹，这是怎么回事？期待解答，谢谢！

**Comment by lcy0604** [comment]
删除即可

550developer ***@***.***> 于2024年12月30日周一 11:22写道：

**Comment by TK-Operator** [comment]
我是一个深度学习新手，如果我想要进行推理任务，我应该输入哪些命令呢？还是那个测试的命令吗？谢谢回答！

**Comment by lcy0604** [comment]
目前还没有公开测试模型，需要自己按照训练脚本重新训练

550developer ***@***.***> 于2024年12月30日周一 14:51写道：
